/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of OpenCV.xs. Do not edit this file, edit OpenCV.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/GoatKCD/Extractor/OpenCV.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#undef seed

#include <opencv/cv.h>
#include <opencv/highgui.h>
#include <opencv2/highgui/highgui_c.h>
#include <math.h>
#include <stdio.h>


SV* process_lines(char* filename,int minLength) {

    IplImage* src = cvLoadImage( filename, 0 );

	SV* retval = newSV(0);
	if( !src ) {
        return retval;
    }
	int i;
	
    CvSeq* lines = 0;

    IplImage* dst = cvCreateImage( cvGetSize(src), 8, 1 );
    //IplImage* color_dst = cvCreateImage( cvGetSize(src), 8, 3 );

    cvCanny( src, dst, 50, 200, 3 );
    //cvCvtColor( dst, color_dst, CV_GRAY2BGR );

	int rho=50;
	int theta = 50;
	int threshold = 1;

    lines = cvHoughLines2( dst, cvCreateMemStorage(0), CV_HOUGH_PROBABILISTIC, 1, CV_PI/180, rho, theta, threshold );

	AV* plines = newAV();
	for( i = 0; i < lines->total; i++ ) {
		CvPoint* line = (CvPoint*)cvGetSeqElem(lines,i);
		// mostly straight lines, lank you very much.
        if (abs(line[0].x-line[1].x)<3 || abs(line[0].y-line[1].y)<3) {
			int tmp;
			// fmake sure they all point from the top left
			if (line[0].x>line[1].x) {
				tmp = line[0].x;	
				line[0].x = line[1].x;
				line[1].x=tmp;
			}
			if (line[0].y>line[1].y) {
				tmp = line[0].y;    
                line[0].y = line[1].y;
                line[1].y=tmp;
            }
			int lineLength=(line[1].x-line[0].x)+(line[1].y-line[0].y);
			if (lineLength>=minLength) {
				AV* ltt;
				ltt  = newAV();
				for (int j=0;j<2;j++) {
					av_push(ltt,newSViv((int)line[j].x));
					av_push(ltt,newSViv(line[j].y));
				}
				av_push(plines,newRV((SV*)ltt));
				//cvLine( color_dst, line[0], line[1], CV_RGB(0,0,0xff), 1, CV_AA, 0 );
        	}
		}
    }

	//cvNamedWindow( "Hough", 1 );
    //cvShowImage( "Hough", color_dst );
    //cvWaitKey(0);
	return newRV((SV*)plines);
}


#line 85 "lib/GoatKCD/Extractor/OpenCV.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 229 "lib/GoatKCD/Extractor/OpenCV.c"

XS_EUPXS(XS_GoatKCD__Extractor__OpenCV_getlines); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GoatKCD__Extractor__OpenCV_getlines)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "input, minLength");
    {
	char*	input = (char *)SvPV_nolen(ST(0))
;
	int	minLength = (int)SvIV(ST(1))
;
	SV *	RETVAL;
#line 83 "lib/GoatKCD/Extractor/OpenCV.xs"
		RETVAL = process_lines(input,minLength);
#line 245 "lib/GoatKCD/Extractor/OpenCV.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_GoatKCD__Extractor__OpenCV_echo); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GoatKCD__Extractor__OpenCV_echo)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "input");
    {
	int	input = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
#line 92 "lib/GoatKCD/Extractor/OpenCV.xs"
    RETVAL = (input % 2 == 0);
#line 266 "lib/GoatKCD/Extractor/OpenCV.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_GoatKCD__Extractor__OpenCV); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_GoatKCD__Extractor__OpenCV)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("GoatKCD::Extractor::OpenCV::getlines", XS_GoatKCD__Extractor__OpenCV_getlines);
        newXS_deffile("GoatKCD::Extractor::OpenCV::echo", XS_GoatKCD__Extractor__OpenCV_echo);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

