#!/usr/bin/env perl

use Moose;
use lib qw(./lib);
use GoatKCD::CLI;
use Getopt::Long;
use Data::Dumper;
use feature qw(say);

my $cli = GoatKCD::CLI->new();

if (scalar(@ARGV)) {

	$cli->commandline(@ARGV);

} else {
	$cli->main();
}
