#!/usr/bin/env perl

use GoatKCD;
use Data::Dumper;
use Term::ReadLine;
use Web::Scraper;
use URI;
use feature qw(say);

my $line;
my $gkcd = GoatKCD->new();
my $term = Term::ReadLine->new();


if (-f $ARGV[0]) {
	$gkcd->summon_the_goatman($ARGV[0])->Display();
	exit;
}

while ($line ne "quit") {
	$line = $term->readline("Comic Number: ");
	my ($command,@args) = split(/ /,$line);
	if (main->can($command)) {
		main->$command(@args);
	} else {
		usage();
	}
}

sub quit {
	exit;
}

sub show {
	my ($class,$file) = @_;

	summon($file)->Display();
}

sub beastmode {
	my $class = shift;
	my $flag = shift;

	$gkcd->beastmode($gkcd->beastmode^1);
}

sub minlength {
	my ($class,$flag) = @_;

	$gkcd->processor->min_line_length($flag);
}

sub debug {
	my ($class) = @_;

	$gkcd->debug($gkcd->debug^1);
}

sub stinger {
	my ($class,$img) = @_;

	if (-f $img) {
		$gkcd->stinger($gkcd->load_img($img));
	}
}

sub minrect{
	my ($class,$size) = @_;

	$gkcd->processor->min_rect_thickness($size);
}

sub proximity {
	my ($class,$prox) = @_;

	$gkcd->processor->collapse_proximity($prox);
}

sub comic {
	my ($class,$id) = @_;

	my $res = scraper {
		process 'div#comic > img',img=>'@src';
	}->scrape(URI->new("https://xkcd.com/$id"));

	summon($res->{img})->Display();
}

sub summon {
	my $what = shift;
	return $gkcd->summon_the_goatman($what);
}
sub usage() {
	say "LOL";
}	
