=head1 NAME

GoatKCD - Making Your Wildest Dreams Come True

=head1 SYNOPSIS

 use GoatKCD;

 my $gkcd = GoatKCD->new();
 my $img = $gkcd->summon_the_goatman("http://i0.kym-cdn.com/photos/images/newsfeed/000/143/193/cad-20080602-358b1.jpg");

 my $x = `"echo '8====D' > /dev/urmom`
 
=head1 DESCRIPTION

 .............. ...,;;;;,'''''...',,;:::ccclllc:;,;;::::ccccclllllllllllllooollllcccllloooooooolllllllcc::cc::;,;;;;;::::
 ..................,;;;,''''''...',,;;:ccccccclc:;;;:::cccclllllllllllllooooooolllccllooooooooollllllllcccc:;,,,;:::::::;
 ...........   ....,;,;,''''''...',,;;;::ccccccc::;;:cccclllllllllllllloooolooooollcllooooooddoollllllllccc:,,;::c::::::;
 ..........    ....,;,;,'''''....'',,;;;::clcccc::;::ccclllllllllllllloooollllollllccllolooodddoolccllllccc::::cc::::;::;
 ........      ....,;,,,'''''....'''',,;;::cccc:::;;:cccllllllllccccllooolccllollllccclooooooooolllccclllcc:::::::::;;;;.
 ........       ...,;,,''''''.....'.'',,;;;:cccc:;;;:cccclllccccccccllllccclllollllccclooooooollllllcccclcc::;:::;::;;,. 
 .......        ...,;,,,''''''....'''''',;;;:ccll:;;:::cccccccc::cccclllllllooooooooooodddddddddooooolllcccc:;;;;;;;,'.  
                ..',;;;,'''''''....''''.',,;:cloolc:::::c::::::cllooooooooddxxxxxxxxxxxxxxxxxxxxxxdddddooollc:;,,,,,'....
               ...',;;;,,'''..'.....'''.'',;:cclollc;;;;::cclooddddoooddxxxkkOOkkkkxxxxxxxxxxkkkxxxxdddddoooolc;,'...'',,
                ..';;;:;,'''..'...........,;;;:ccclc;;;cloodddddooodddxxkkkkkkkkkkkxddddxxddddddddxxxxxxxxddddl::cclolc:;
                ..';;;:;;,'''.'...........''',:cllllccloddddoooddddxxxkkkkkkkkxxxdddoooodoooooddxxkkkkkkxxxdolloxkkkkxdl:
                ..';;;:;;;,,'''...'........',;:cllccccccccooddddxxkkkOOOOOOOOOOkkxxdddoooooodddddddxxxxxdddddxkOOOOkOOxdc
                 .,;;::;;;;,,''............',;::cccccc:;::clodddddxkkOO00KKKKK00OkkxdddddoooooddddddddoooxkO000OOkkO00Oko
                 .';,;:;;;;;,,'...........'',,:cccccccccclloooddxkkkkkkO0KKK00Okkxxdooooooollllooolc:loooxkOOOOOO00KK00Ox
                ..,;,;:;;;;;;,'...........',,,;;::cllllllloodddxkOOOOOkxxkkkkxddoollcccccccccccc:::ccoddxkO0KKKKK00OO0Okd
                ..,;;;:;;;;;;;,'............,;;;;:cccloooolloooxkOOOOOOkkkxkkxxolccllcclllllccc:,;coxxxxOO0000Okkxkkkkkkx
                 .,;;;:;;;;;;;,'........'...',,;;:cc:codolllodxk00OOkkkOkkxkkkdodxxdlc:cccccc:::;;:ldoldkkkkkkxxxxxkO000O
                 .,;;;:;;;;;;;,'.......';c:'..',::cc::cooolldxO0000OkkOOkxxxkxoooddl:::::::;:ccc:;;;:loxO00KK000OOkkkkOkx
                 .,;;;:;;;;;;,'........;lddoc:,',:cccccllccoxxk00OOOOkkkkxdxkxxl:;;;,;;;;;;,;;:::;,';lxO0OOO00Okkxxddoll:
                ..,;;;:;;;;;,,'.......'cdxooxOOc'';:cc::clcldxkO00OOkxxxxooxxxdl:;,',,,,,;,,,;:cc;,',cxkOkxxddxdddddxxxdl
                ..,,;;;;;;;;,'........;oddodk0Kk:',;:cc:::clloxO00Okxxxkxxkkkkkxo:;:;;;:::;,,;;;;;,,ccldxkkkkkOOOOOOOOOxd
                ..,,;;;;;;;,''.......':ooddxkO00l,;;::cc:;:cooodxxxddxxxxdxxxdxxdc;;;;;;::;,,,;;:;,,cccdkO0000OOkxxkxdol:
                ..,,;;;;;;;,'........'clodxxkO00o,,:cccc:::cllloddddddddddddddddol:;;;;:cc:::::ccc:;;::lxkkkxxdooloolc::c
                ..,,;;;;;;,,'........,coddxkkk0Oo;,;:ccllc:clodxkOOOxxkkkkkOOkxdocc:ccccclllllllllllccccllllllloooddolllo
                 .,,,;;;;;,,'........,codddxkkOkcclcc::ccc::cclodxkkxxkkkOO000Okoc:cclodddddddoolllllllllllodddxxxxolcccl
                 .,,,;;;;;,,'........,cloddxxxkxlclddolollcc:::ccccllolooddxxddocccllooddddooollccccccclloddxxxxdolllolll
                 .,,,;;;;;,''........,cooddxxxxkxocldxOOxllloooooolccccccccccc:::::cccccccccccclllccclllooddddddlcllolccc
                 .,,,;;;;;,'.........,cooddddxxxkxl:ldkOxdddddooolllllccc:::;;;:::::cccccccccccccc::ccccllllllooccclllccc
                 .,,,;;;;,,'.........,cloooddddxxkdc:ldxxxxxdddddllllcc:::;;;;;;:::ccccc:::::cc::;;;::::ccccccccllloodddd
                 .,,,;;;,,'........'',:cloodddddddxdccloollllllllllllc::;;;;,,,,;:::::::::ccccc:;,,,;;:::cccllllllloodddd
                 .,,,;;,,'........''',:ccllooodddddddooooooollllllllcc::;,,,;;,',;::::::::cccc:;,,,,,,;;::ccclllllllooooo
                 .,,,;;,,........',,,,::cclllooooddddddddoooolllllcc::;;,,;;;;,'',;;::::;:::::,..',,,,,;;;:ccclllllllllll
                 .,,,;;,'........',,,,;::cccllloooooooooooolllllccc:;;,,,,,''....',,;::;;:::;,.. ..'',,,;;::cccclllllllll
                 .,,,;;,.........,,,,;;::::ccccllllllooolllccccc::;;;,,'......  .,',;;;;;;;;;,........'',;;:::cccccclllll
                 .,,,;;'........',,,,;;::::::ccclllllllcccc:::::;;;,,,''......  .,,,;;;;;;,,;,'.........,;;;;;::::::ccccc
                 .',,;,'........',,,,;;:::c:::ccccccccc::::;;;;;;;;,,;;,......  .',;;;;;;;;;;;,'.........,,,,;;;;;::::ccc
                 .',,;,.........'''',,;:::c:::ccccccc:::::;;;;;;;;;;;;;'......  .';;:::::::;;;;;,'........',;;;;;;;;::ccc
                 .'',,,..........'''',;;::::::ccccc:::;;;;;,,,,,,;;;;;,'.....   .,;;::::::::;;;;;;,'........',,;;;;;::::c
                 .'',,'............'',;;::::::::::::;;;,,,,,,,,;;;;;;;,'.....   .,,;;:::::::;;;;;;;;,.........,,,,,;;;:::
                 .'',,'.............',,;;;::::::::;;;,,,,,,,;;;;;;;;;;,'.....    .,;;;;;;:::;;;;:;;:;,'........',,,,,;;;:
                 .'',,'.............',,;;;;;::::;;;,,,'''.'''''''''..'......     ..',,,;;;;;,,;;;;;;;;,'........',,',,;;;
                 .'',,,.............'',,;;;;;;;,,,,,'''.....................    .....'''''''....'''',,,''.........'''',,,
                 .'',,,'........ ...'',,,,,,,,'''''..........................    .'''''''...............................'
 ,,,'..          .''',,'........ ...''''''''..'''.............................   ..'''''.................................
 looll:'.        .''','......... ....''''''..'''................................  ..'''..................................
=cut

=head1 USAGE

 Look at teh code scrub

=cut
=head1 DEPENDENCIES

 OpenCV2

=head1 THANKS TO

 Inpired by the fine folks at GoatKCD (https://goatkcd.com)

=cut


