#!/usr/bin/env perl

use Moose;
use lib qw(./lib);
use GoatKCD::CLI;
use Getopt::Long;
use Data::Dumper;
use feature qw(say);

my $cli = GoatKCD::CLI->new();

#test 

if (scalar(@ARGV)) {
	$cli->cl(1);
	$cli->commandline(@ARGV);

} else {
	$cli->main();
}
